In [3]:
import pandas as pd
df = pd.read_csv("sales_data_sample.csv", encoding='latin1',usecols=['ORDERDATE' ,'SALES'])

In [4]:
df

        SALES        ORDERDATE
0     2871.00   2/24/2003 0:00
1     2765.90    5/7/2003 0:00
2     3884.34    7/1/2003 0:00
3     3746.70   8/25/2003 0:00
4     5205.27  10/10/2003 0:00
...       ...              ...
2818  2244.40   12/2/2004 0:00
2819  3978.51   1/31/2005 0:00
2820  5417.57    3/1/2005 0:00
2821  2116.16   3/28/2005 0:00
2822  3079.44    5/6/2005 0:00

[2823 rows x 2 columns]

In [7]:
df['ORDER_DATE'] = pd.to_datetime(df['ORDERDATE'])

In [10]:
new=df.drop('ORDERDATE', axis=1)

In [36]:
roll_data = new['SALES'].rolling(window =7 ).mean()

In [37]:
new['rolling_sales'] = roll_data
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [39]:
new_df =new.dropna()
new_df.drop('rolling' ,axis=1)

         SALES ORDER_DATE  rolling_sales
6      2497.77 2003-11-11    3492.962857
7      5512.32 2003-11-18    3870.294286
8      2168.54 2003-12-01    3784.957143
9      4708.44 2004-01-15    3902.685714
10     3965.66 2004-02-20    3933.965714
11     2333.12 2004-04-05    3523.658571
12     3188.64 2004-05-18    3482.070000
13     3676.76 2004-06-28    3650.497143
14     4177.35 2004-07-23    3459.787143
15     4099.68 2004-08-27    3735.664286
16     2597.39 2004-09-30    3434.085714
17     4394.38 2004-10-15    3495.331429
18     4358.04 2004-11-02    3784.605714
19     4396.14 2004-11-15    3957.105714
20     7737.93 2004-11-24    4537.272857
21     1451.00 2004-12-17    4147.794286
22      733.11 2005-02-03    3666.855714
23     3207.12 2005-03-03    3753.960000
24     2434.56 2005-04-08    3473.985714
25     7516.08 2005-05-13    3925.134286
26     5404.62 2003-01-29    4069.202857
27     7209.11 2003-03-24    3993.657143
28     7329.06 2003-05-28    4833.380000
29     7374.10 2003-07-24    5782.092857
30    10993.50 2003-09-19    6894.432857
31     4860.24 2003-10-20    7240.958571
32     8014.82 2003-11-06    7312.207143
33     5372.57 2003-11-13    7307.628571
34     7290.36 2003-11-25    7319.235714
35     9064.89 2003-12-05    7567.211429
36     6075.30 2004-01-29    7381.668571
37     6463.23 2004-03-10    6734.487143
38     6120.34 2004-05-04    6914.501429
39     7680.64 2004-06-15    6866.761429
40     4905.39 2004-07-19    6800.021429
41     8014.82 2004-08-17    6903.515714
42     7136.19 2004-09-08    6627.987143
43    10172.70 2004-10-11    7213.330000
44    11623.70 2004-10-21    7950.540000
45     6000.40 2004-11-04    7933.405714
46     3003.00 2004-11-18    7265.171429
47     3944.70 2004-11-29    7127.930000
48     5691.84 2004-12-10    6796.075714
49     4514.92 2005-01-20    6421.608571
50     8254.80 2005-02-17    6147.622857
51     2416.56 2005-03-09    4832.317143
52     4140.23 2005-05-01    4566.578571
53    12001.00 2005-05-31    5852.007143
54     3896.49 2003-02-24    5845.120000
55     2793.86 2003-04-29    5431.122857
56     3307.77 2003-07-01    5258.672857
57     5192.95 2003-08-25    4821.265714
58     5016.83 2003-10-10    5192.732857
59     3660.93 2003-10-28    5124.261429
60     4695.60 2003-11-11    4080.632857
61     3660.92 2003-11-18    4046.980000
62     3025.92 2003-12-01    4080.131429
63     3009.09 2004-01-12    4037.462857
64     5422.39 2004-02-20    4070.240000
65     2852.08 2004-04-03    3760.990000
66     5756.52 2004-05-18    4060.360000
67     4472.00 2004-06-28    4028.417143
68     2904.44 2004-07-23    3920.348571
69     6484.59 2004-08-27    4414.444286
70     3757.26 2004-09-27    4521.325714
71     4043.96 2004-10-15    4324.407143
72     5566.50 2004-11-02    4712.181429
73     3176.00 2004-11-15    4343.535714
74     2756.80 2004-11-23    4098.507143
75     1329.90 2004-12-17    3873.572857
76     5288.01 2005-02-02    3702.632857
77     2225.50 2005-03-03    3483.810000
78     5833.80 2005-04-07    3739.501429
79     5887.35 2005-05-13    3785.337143
80     6065.55 2003-02-24    4198.130000
81     9264.86 2003-04-29    5127.852857
82     7023.98 2003-07-01    5941.292857
83     5176.38 2003-08-25    5925.345714
84     4132.70 2003-10-10    6197.802857
85     4183.00 2003-10-28    5961.974286
86     8892.90 2003-11-11    6391.338571
87     8714.70 2003-11-18    6769.788571
88     8065.89 2003-12-01    6598.507143
89     6123.40 2004-01-12    6469.852857
90     9774.03 2004-02-20    7126.660000
91     7023.90 2004-04-05    7539.688571
92     7078.23 2004-05-18    7953.292857
93     8336.94 2004-06-28    7873.870000
94     6901.92 2004-07-23    7614.901429
95     5438.07 2004-08-27    7239.498571
96     6683.34 2004-09-30    7319.490000
97     4570.40 2004-10-15    6576.114286
98     7667.14 2004-11-02    6668.005714
99     5868.20 2004-11-15    6495.144286
100    2990.13 2004-11-23    5731.314286
101    3664.10 2005-01-05    5268.768571
102    3834.38 2005-02-02    5039.670000
103    1822.17 2005-03-03    4345.217143
104   11886.60 2005-04-08    5390.388571
105    9218.16 2005-05-13    5611.962857
106    7208.00 2003-02-11    5803.362857
107    5004.80 2003-04-28    6091.172857
108    4398.24 2003-06-12    6196.050000
109    5597.76 2003-08-10    6447.961429
110    4526.08 2003-10-06    6834.234286
111    5924.16 2003-10-23    5982.457143
112    3492.48 2003-11-08    5164.502857
113    3854.24 2003-11-14    4685.394286
114    5324.40 2003-11-26    4731.051429
115    5197.92 2004-01-09    4845.291429
116    5997.60 2004-02-19    4902.411429
117    2910.40 2004-05-07    4671.600000
118    3378.24 2004-06-17    4307.897143
119    3508.80 2004-07-21    4310.228571
120    2992.00 2004-08-20    4187.051429
121    3427.20 2004-09-10    3916.022857
122    2692.80 2004-10-14    3558.148571
123    4128.96 2004-11-01    3291.200000
124    3051.71 2004-11-05    3311.387143
125    1201.25 2004-11-21    3000.388571
126    1962.22 2004-12-02    2779.448571
127    2624.64 2004-12-15    2726.968571
128    4046.25 2005-01-31    2815.404286
129    4846.70 2005-02-23    3123.104286
130    3370.56 2005-03-17    3014.761429
131    9661.44 2005-04-01    3959.008571
132    2764.88 2005-05-06    4182.384286
133    5398.26 2003-01-29    4673.247143
134    4305.28 2003-04-01    4913.338571
135    3347.74 2003-05-28    4813.551429
136    3188.12 2003-07-24    4576.611429
137    3191.20 2003-09-19    4550.988571
138    3536.82 2003-10-21    3676.042857
139    5362.83 2003-11-06    4047.178571
140    3433.36 2003-11-13    3766.478571
141    4263.74 2003-11-25    3760.544286
142    4076.19 2003-12-09    3864.608571
143    7020.48 2004-02-04    4412.088571
144    6426.50 2004-03-11    4874.274286
145    4591.72 2004-05-04    5024.974286
146    4033.38 2004-06-15    4835.052857
147    4302.08 2004-07-19    4959.155714
148    7020.64 2004-08-19    5352.998571
149    3855.90 2004-09-08    5321.528571
150    6680.78 2004-10-13    5273.000000
151    6678.00 2004-10-22    5308.928571
152    2851.54 2004-11-04    5060.331429
153    3188.12 2004-11-19    4939.580000
154    4428.00 2004-11-29    4957.568571
155    5780.92 2004-12-10    4780.465714
156    2297.05 2005-01-20    4557.772857
157    6231.54 2005-02-17    4493.595714
158    1735.30 2005-03-09    3787.495714
159    4427.73 2005-05-01    4012.665714
160    5894.94 2005-05-31    4399.354286
161    5265.15 2003-03-03    4518.947143
162    7599.90 2003-05-08    4778.801429
163    8008.56 2003-07-02    5594.731429
164    9245.76 2003-09-05    6025.334286
165    8296.35 2003-10-10    6962.627143
166    5019.90 2003-11-04    7047.222857
167    5411.07 2003-11-12    6978.098571
168    3840.90 2003-11-20    6774.634286
169    3930.40 2003-12-02    6250.420000
170    7498.90 2004-01-15    6177.611429
171    4517.91 2004-02-22    5502.204286
172    5774.72 2004-04-09    5141.971429
173    3922.56 2004-06-01    4985.208571
174    9160.36 2004-07-06    5520.821429
175    9631.00 2004-08-02    6347.978571
176    3432.24 2004-08-30    6276.812857
177    5521.89 2003-10-04    5994.382857
178    6934.62 2004-10-16    6339.627143
179    6876.11 2004-11-03    6496.968571
180    2930.27 2004-11-15    6355.212857
181    3584.25 2004-11-24    5558.625714
182    2817.87 2005-01-06    4585.321429
183    3420.00 2005-02-03    4583.572857
184    2575.04 2005-03-03    4162.594286
185    1961.28 2005-05-17    3452.117143
186    8690.36 2003-02-11    3711.295714
187    6034.38 2003-04-16    4154.740000
188   11279.20 2003-06-03    5254.018571
189    8023.29 2003-08-08    5997.650000
190    4904.00 2003-09-28    6209.650000
191    8594.52 2003-10-22    7069.575714
192    7474.50 2003-11-06    7857.178571
193    3883.74 2003-11-14    7170.518571
194    8887.70 2003-11-26    7578.135714
195    8602.92 2004-01-02    7195.810000
196    7181.44 2004-02-12    7075.545714
197    8378.58 2004-03-19    7571.914286
198   10606.20 2004-05-05    7859.297143
199    5818.40 2004-07-20    7622.711429
200    7071.27 2004-08-20    8078.072857
201    8411.56 2004-09-09    8010.052857
202    6570.76 2004-10-14    7719.744286
203    7975.44 2004-10-22    7833.172857
204    2688.00 2004-11-05    7020.232857
205    1888.26 2004-11-20    5774.812857
206    2513.28 2004-11-01    5302.652857
207    4764.48 2004-12-15    4973.111429
208    3560.64 2005-01-23    4280.122857
209    3823.64 2005-02-17    3887.677143
210    2280.96 2005-03-17    3074.180000
211    8677.80 2005-05-05    3929.865714
212    3394.98 2003-01-29    4145.111429
213    3415.44 2003-03-26    4273.991429
214    2439.57 2003-05-28    3941.861429
215    4829.80 2003-07-24    4123.170000
216    4100.10 2003-09-19    4162.664286
217    6563.06 2003-10-21    4774.392857
218    6817.22 2003-11-06    4508.595714
219    6163.94 2003-11-13    4904.161429
220    4933.92 2003-11-25    5121.087143
221    4056.36 2003-12-05    5352.057143
222    5759.42 2004-02-02    5484.860000
223    3451.00 2004-03-11    5392.131429
224    5920.40 2004-05-04    5300.322857
225    6668.24 2004-06-15    5279.040000
226    4094.72 2004-07-19    4983.437143
227    2938.50 2004-08-19    4698.377143
228    6387.80 2004-09-08    5031.440000
229    6396.00 2004-10-11    5122.380000
230    2669.10 2004-10-22    5010.680000
231    4784.13 2004-11-04    4848.355714
232    3273.93 2004-11-18    4363.454286
233    3586.43 2004-11-29    4290.841429
234    5960.36 2004-12-10    4722.535714
235    8470.14 2005-01-20    5020.012857
236    2952.00 2005-02-17    4528.012857
237    2464.80 2005-03-09    4498.827143
238    6232.00 2005-05-01    4705.665714
239    7969.36 2005-05-31    5376.441429
240    3036.60 2003-02-24    5297.894286
241    8284.00 2003-05-07    5629.842857
242    2711.20 2003-07-01    4807.137143
243    8339.80 2003-08-25    5576.822857
244    6238.84 2003-10-10    6115.971429
245    4639.25 2003-11-04    5888.435714
246    6747.60 2003-11-11    5713.898571
247    4512.48 2003-11-18    5924.738571
248    4029.00 2003-12-01    5316.881429
249    4771.80 2004-01-15    5611.252857
250    6087.94 2004-02-21    5289.558571
251    4193.28 2004-04-05    4997.335714
252    7552.28 2004-05-18    5413.482857
253    6434.40 2004-06-28    5368.740000
254    5181.50 2004-08-02    5464.314286
255    6863.92 2004-08-27    5869.302857
256    4157.04 2004-09-30    5781.480000
257    4660.24 2004-10-15    5577.522857
258    4111.80 2004-11-03    5565.882857
259    3542.64 2004-11-15    4993.077143
260    8118.55 2004-11-24    5233.670000
261    3877.06 2005-01-05    5047.321429
262    3867.08 2005-02-03    4619.201429
263    5951.44 2005-03-03    4875.544286
264    8648.64 2005-04-08    5445.315714
265    3447.78 2005-05-13    5350.455714
266    5958.50 2003-01-31    5695.578571
267    5911.64 2003-04-16    5380.305714
268    7366.44 2003-06-03    5878.788571
269    4985.64 2003-08-08    6038.582857
270    5393.64 2003-09-28    5958.897143
271    4880.02 2003-10-22    5420.522857
272    8378.69 2003-11-06    6124.938571
273    4038.21 2003-11-14    5850.611429
274    3807.12 2003-11-26    5549.965714
275    3142.36 2004-01-02    4946.525714
276    4713.60 2004-02-12    4907.662857
277    7016.31 2004-03-15    5139.472857
278    4381.25 2004-05-05    5068.220000
279    4283.01 2004-07-20    4483.122857
280    4364.82 2004-08-20    4529.781429
281    4242.24 2004-09-09    4591.941429
282    4982.70 2004-10-14    4854.847143
283    6393.54 2004-10-22    5094.838571
284    1466.91 2004-11-05    4302.067143
285    4059.33 2004-11-20    4256.078571
286    4801.52 2004-11-01    4330.151429
287    2711.66 2004-12-10    4093.985714
288    5862.00 2005-01-26    4325.380000
289    4071.85 2005-02-17    4195.258571
290    8236.75 2005-05-05    4458.574286
291    6130.35 2003-03-03    5124.780000
292    3693.34 2003-05-08    5072.495714
293    6031.68 2003-07-02    5248.232857
294    3494.94 2003-09-05    5360.130000
295    5294.14 2003-10-11    5279.007143
296    5464.69 2003-11-04    5477.984286
297    2860.76 2003-11-12    4709.985714
298    5590.00 2003-11-20    4632.792857
299    2254.80 2003-12-02    4427.287143
300    4946.76 2004-01-16    4272.298571
301    2495.50 2004-02-22    4129.521429
302    3167.38 2004-04-09    3825.698571
303    2402.84 2004-06-01    3388.291429
304    2454.54 2004-07-06    3330.260000
305    5464.69 2004-08-02    3312.358571
306    4756.50 2004-08-30    3669.744286
307    3984.60 2003-10-04    3532.292857
308    3100.32 2004-10-16    3618.695714
309    4850.30 2004-11-03    3859.112857
310    3846.98 2004-11-15    4065.418571
311    4220.92 2004-11-24    4317.758571
312    3288.82 2005-01-06    4006.920000
313    3987.20 2005-02-08    3897.020000
314    1809.50 2005-03-03    3586.291429
315    1092.20 2005-05-17    3299.417143
316    4566.05 2003-02-11    3258.810000
317    5938.14 2003-04-16    3557.547143
318    8138.76 2003-06-03    4117.238571
319    9470.94 2003-08-08    5000.398571
320    7036.89 2003-09-28    5436.068571
321    5559.03 2003-10-22    5971.715714
322    7872.50 2003-11-06    6940.330000
323    7886.20 2003-11-14    7414.637143
324    7232.16 2003-11-26    7599.497143
325    3114.40 2004-01-02    6881.731429
326    5045.22 2004-02-12    6249.485714
327    6952.12 2004-03-19    6237.375714
328    4157.73 2004-05-05    6037.190000
329    7962.24 2004-07-20    6050.010000
330    3778.80 2004-08-20    5463.238571
331    8253.00 2004-09-09    5609.072857
332    3633.40 2004-10-14    5683.215714
333    6913.80 2004-10-22    5950.155714
334    2583.60 2004-11-05    5326.081429
335    3105.62 2004-11-20    5175.780000
336    4408.56 2004-12-01    4668.111429
337    3042.41 2004-12-15    4562.912857
338    5941.50 2005-01-26    4232.698571
339    3241.90 2005-02-17    4176.770000
340    6109.29 2005-03-23    4061.840000
341    3387.78 2005-05-05    4176.722857
342    3485.82 2003-03-03    4231.037143
343    2042.88 2003-05-08    3893.082857
344    1800.24 2003-07-02    3715.630000
345    1340.64 2003-09-05    3058.364286
346    1762.08 2003-10-10    2846.961429
347    2298.24 2003-11-04    2302.525714
348    1628.00 2003-11-12    2051.128571
349    1939.20 2003-11-20    1830.182857
350    3651.56 2003-12-02    2059.994286
351    2591.96 2004-01-15    2173.097143
352    2864.17 2004-02-22    2390.744286
353    1484.20 2004-04-09    2351.047143
354    2254.25 2004-06-01    2344.762857
355    2681.35 2004-07-06    2495.241429
356    3184.02 2004-08-02    2673.072857
357    2846.63 2004-08-30    2558.082857
358    1685.42 2003-10-04    2428.577143
359    3988.60 2004-10-16    2589.210000
360    2789.96 2004-11-03    2775.747143
361    3607.56 2004-11-15    2969.077143
362    3368.16 2004-11-24    3067.192857
363    2775.08 2005-01-06    3008.772857
364    1627.92 2005-02-09    2834.671429
365    2529.36 2005-03-03    2955.234286
366    3065.78 2005-05-17    2823.402857
367    4615.78 2003-01-31    3084.234286
368    5723.78 2003-04-04    3386.551429
369    2559.60 2003-06-03    3271.042857
370    2140.11 2003-08-01    3180.332857
371    3327.60 2003-09-21    3423.144286
372    6825.60 2003-10-22    4036.892857
373    3543.28 2003-11-06    4105.107143
374    4516.22 2003-11-14    4090.884286
375    6445.46 2003-11-25    4193.981429
376    3384.36 2003-12-09    4311.804286
377    4891.68 2004-02-10    4704.885714
378    4521.96 2004-03-11    4875.508571
379    5069.66 2004-05-05    4624.660000
380    6541.20 2004-06-15    5052.934286
381    3012.27 2004-07-20    4838.084286
382    5247.18 2004-08-19    4666.901429
383    2214.87 2004-09-08    4499.831429
384    4773.18 2004-10-13    4482.902857
385    6185.70 2004-10-22    4720.580000
386    1517.88 2004-11-05    4213.182857
387    6372.60 2004-11-20    4189.097143
388    5232.96 2004-12-01    4506.338571
389    2694.72 2004-12-10    4141.701429
390    1749.79 2005-01-23    4075.261429
391    2130.56 2005-02-17    3697.744286
392    5951.34 2005-05-03    3664.264286
393    4692.60 2005-05-31    4117.795714
394    3731.04 2003-03-03    3740.430000
395    2142.00 2003-05-08    3298.864286
396    2838.81 2003-07-02    3319.448571
397    3230.37 2003-09-05    3530.960000
398    5182.00 2003-10-11    3966.880000
399    4391.10 2003-11-04    3743.988571
400    4477.32 2003-11-12    3713.234286
401    3544.56 2003-11-20    3686.594286
402    5195.85 2003-12-02    4122.858571
403    4180.44 2004-01-16    4314.520000
404    2684.43 2004-02-22    4236.528571
405    1958.88 2004-04-12    3776.082857
406    4910.57 2004-06-01    3850.292857
407    4468.40 2004-07-06    3849.018571
408    3127.88 2004-08-04    3789.492857
409    2675.13 2004-08-30    3429.390000
410    2807.61 2003-10-04    3233.271429
411    2504.75 2004-10-16    3207.602857
412    2984.88 2004-11-04    3354.174286
413    2524.86 2004-11-15    3013.358571
414    4136.00 2004-11-24    2965.872857
415    4068.70 2005-01-06    3100.275714
416    5182.00 2005-02-09    3458.400000
417    5243.79 2005-03-03    3806.425714
418    9048.16 2005-04-14    4741.198571
419    3832.64 2005-05-17    4862.307143
420    3920.00 2003-01-29    5061.612857
421    4916.66 2003-03-26    5173.135714
422    3857.00 2003-05-28    5142.892857
423    4181.44 2003-07-24    4999.955714
424    4641.00 2003-09-19    4913.842857
425    3570.12 2003-10-21    4131.265714
426    4480.32 2003-11-06    4223.791429
427    2033.64 2003-11-13    3954.311429
428    1960.14 2003-11-25    3531.951429
429    3966.78 2003-12-05    3547.634286
430    5152.00 2004-01-29    3686.285714
431    3360.00 2004-03-10    3503.285714
432    3451.00 2004-05-04    3486.268571
433    5453.00 2004-06-15    3625.222857
434    4164.12 2004-07-19    3929.577143
435    2800.08 2004-08-17    4049.568571
436    4687.94 2004-09-08    4152.591429
437    4508.00 2004-10-11    4060.591429
438    4181.44 2004-10-21    4177.940000
439    2251.04 2004-11-04    4006.517143
440    1167.25 2004-11-18    3394.267143
441    2083.20 2004-11-29    3096.992857
442    3822.00 2004-12-10    3242.981429
443    3911.49 2005-01-20    3132.060000
444    4704.00 2005-02-17    3160.060000
445    2467.90 2005-03-09    2915.268571
446    3213.00 2005-05-01    3052.691429
447    7182.00 2005-05-31    3911.941429
448    4379.18 2003-03-10    4239.938571
449    5004.80 2003-05-08    4408.910000
450    3644.75 2003-07-04    4370.804286
451    2702.04 2003-09-11    4084.810000
452    3764.88 2003-10-17    4270.092857
453    4508.00 2003-11-05    4455.092857
454    5418.16 2003-11-12    4203.115714
455    3300.66 2003-11-20    4049.041429
456    6182.40 2003-12-02    4217.270000
457    4186.73 2004-01-16    4294.695714
458    4529.28 2004-02-22    4555.730000
459    5628.89 2004-04-13    4822.017143
460    3054.48 2004-06-01    4614.371429
461    2526.51 2004-07-06    4201.278571
462    4667.86 2004-08-06    4396.592857
463    6499.32 2004-08-30    4441.867143
464    5917.78 2003-10-05    4689.160000
465    6231.91 2004-10-16    4932.392857
466    5803.14 2004-11-04    4957.285714
467    6434.02 2004-11-17    5440.077143
468    6454.40 2004-11-24    6001.204286
469    4196.80 2004-12-09    5933.910000
470    2611.80 2005-01-07    5378.550000
471    5895.05 2005-02-09    5375.302857
472    3375.72 2005-03-04    4967.275714
473    8374.69 2005-04-15    5334.640000
474    4464.24 2005-05-17    5053.242857
475    4808.31 2003-01-10    4818.087143
476    3288.78 2003-03-25    4688.370000
477    3254.72 2003-05-21    4780.215714
478    3184.94 2003-07-16    4393.057143
479    5907.50 2003-09-12    4754.740000
480    4389.12 2003-10-18    4185.372857
481    5036.16 2003-11-05    4267.075714
482    2183.25 2003-11-12    3892.067143
483    3106.88 2003-11-21    3866.081429
484    3735.72 2003-12-03    3934.795714
485    2413.26 2004-01-29    3824.555714
486    2953.75 2004-03-02    3402.591429
487    4684.80 2004-04-29    3444.831429
488    3248.70 2004-06-08    3189.480000
489    5239.50 2004-08-17    3626.087143
490    4567.98 2004-09-03    3834.815714
491    3535.35 2004-10-11    3806.191429

In [34]:
new_df.head(100)

        SALES ORDER_DATE   rolling  rolling_sales
10    3965.66 2004-02-20  27537.76       27537.76
15    4099.68 2004-08-27  26149.65       26149.65
20    7737.93 2004-11-24  31760.91       31760.91
25    7516.08 2005-05-13  27475.94       27475.94
30   10993.50 2003-09-19  48261.03       48261.03
35    9064.89 2003-12-05  52970.48       52970.48
40    4905.39 2004-07-19  47600.15       47600.15
45    6000.40 2004-11-04  55533.84       55533.84
50    8254.80 2005-02-17  43033.36       43033.36
55    2793.86 2003-04-29  38017.86       38017.86
60    4695.60 2003-11-11  28564.43       28564.43
65    2852.08 2004-04-03  26326.93       26326.93
70    3757.26 2004-09-27  31649.28       31649.28
75    1329.90 2004-12-17  27115.01       27115.01
80    6065.55 2003-02-24  29386.91       29386.91
85    4183.00 2003-10-28  41733.82       41733.82
90    9774.03 2004-02-20  49886.62       49886.62
95    5438.07 2004-08-27  50676.49       50676.49
100   2990.13 2004-11-23  40119.20       40119.20
105   9218.16 2005-05-13  39283.74       39283.74
110   4526.08 2003-10-06  47839.64       47839.64
115   5197.92 2004-01-09  33917.04       33917.04
120   2992.00 2004-08-20  29309.36       29309.36
125   1201.25 2004-11-21  21002.72       21002.72
130   3370.56 2005-03-17  21103.33       21103.33
135   3347.74 2003-05-28  33694.86       33694.86
140   3433.36 2003-11-13  26365.35       26365.35
145   4591.72 2004-05-04  35174.82       35174.82
150   6680.78 2004-10-13  36911.00       36911.00
155   5780.92 2004-12-10  33463.26       33463.26
160   5894.94 2005-05-31  30795.48       30795.48
165   8296.35 2003-10-10  48738.39       48738.39
170   7498.90 2004-01-15  43243.28       43243.28
175   9631.00 2004-08-02  44435.85       44435.85
180   2930.27 2004-11-15  44486.49       44486.49
185   1961.28 2005-05-17  24164.82       24164.82
190   4904.00 2003-09-28  43467.55       43467.55
195   8602.92 2004-01-02  50370.67       50370.67
200   7071.27 2004-08-20  56546.51       56546.51
205   1888.26 2004-11-20  40423.69       40423.69
210   2280.96 2005-03-17  21519.26       21519.26
215   4829.80 2003-07-24  28862.19       28862.19
220   4933.92 2003-11-25  35847.61       35847.61
225   6668.24 2004-06-15  36953.28       36953.28
230   2669.10 2004-10-22  35074.76       35074.76
235   8470.14 2005-01-20  35140.09       35140.09
240   3036.60 2003-02-24  37085.26       37085.26
245   4639.25 2003-11-04  41219.05       41219.05
250   6087.94 2004-02-21  37026.91       37026.91
255   6863.92 2004-08-27  41085.12       41085.12
260   8118.55 2004-11-24  36635.69       36635.69
265   3447.78 2005-05-13  37453.19       37453.19
270   5393.64 2003-09-28  41712.28       41712.28
275   3142.36 2004-01-02  34625.68       34625.68
280   4364.82 2004-08-20  31708.47       31708.47
285   4059.33 2004-11-20  29792.55       29792.55
290   8236.75 2005-05-05  31210.02       31210.02
295   5294.14 2003-10-11  36953.05       36953.05
300   4946.76 2004-01-16  29906.09       29906.09
305   5464.69 2004-08-02  23186.51       23186.51
310   3846.98 2004-11-15  28457.93       28457.93
315   1092.20 2005-05-17  23095.92       23095.92
320   7036.89 2003-09-28  38052.48       38052.48
325   3114.40 2004-01-02  48172.12       48172.12
330   3778.80 2004-08-20  38242.67       38242.67
335   3105.62 2004-11-20  36230.46       36230.46
340   6109.29 2005-03-23  28432.88       28432.88
345   1340.64 2003-09-05  21408.55       21408.55
350   3651.56 2003-12-02  14419.96       14419.96
355   2681.35 2004-07-06  17466.69       17466.69
360   2789.96 2004-11-03  19430.23       19430.23
365   2529.36 2005-03-03  20686.64       20686.64
370   2140.11 2003-08-01  22262.33       22262.33
375   6445.46 2003-11-25  29357.87       29357.87
380   6541.20 2004-06-15  35370.54       35370.54
385   6185.70 2004-10-22  33044.06       33044.06
390   1749.79 2005-01-23  28526.83       28526.83
395   2142.00 2003-05-08  23092.05       23092.05
400   4477.32 2003-11-12  25992.64       25992.64
405   1958.88 2004-04-12  26432.58       26432.58
410   2807.61 2003-10-04  22632.90       22632.90
415   4068.70 2005-01-06  21701.93       21701.93
420   3920.00 2003-01-29  35431.29       35431.29
425   3570.12 2003-10-21  28918.86       28918.86
430   5152.00 2004-01-29  25804.00       25804.00
435   2800.08 2004-08-17  28346.98       28346.98
440   1167.25 2004-11-18  23759.87       23759.87
445   2467.90 2005-03-09  20406.88       20406.88
450   3644.75 2003-07-04  30595.63       30595.63
455   3300.66 2003-11-20  28343.29       28343.29
460   3054.48 2004-06-01  32300.60       32300.60
465   6231.91 2004-10-16  34526.75       34526.75
470   2611.80 2005-01-07  37649.85       37649.85
475   4808.31 2003-01-10  33726.61       33726.61
480   4389.12 2003-10-18  29297.61       29297.61
485   2413.26 2004-01-29  26771.89       26771.89
490   4567.98 2004-09-03  26843.71       26843.71
495   1516.62 2004-11-29  26789.67       26789.67
500   4873.05 2005-05-30  30579.31       30579.31
505   1746.60 2003-09-12  21002.12       21002.12